### ISSUE TITLE
Make parameterizing a dataset definition less like writing Python

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1766]
To parameterize a dataset definition, a user needs to do something [like this][1] in their `project.yaml`

```yaml
  model_data_structure_from_dataset_definition:
    run: ehrql:v0
      generate-dataset
      --output output/model_data_structure/dataset.csv
      analysis/model_data_structure/dataset_definition.py
      --
      --day=0
    outputs:
      highly_sensitive:
        rows: output/model_data_structure/dataset.csv
```

and something [like this][2] in their `dataset_definition.py`

```py
parser = argparse.ArgumentParser()
parser.add_argument(
    "--day",
    type=int,
    help="The day a survey was completed, relative to the day the first survey was completed",
)
parser.add_argument(
    "--window",
    type=int,
    default=0,
    help="The number of days +/- the day a survey was completed",
)
args = parser.parse_args()
```

We've had feedback that writing ehrQL is too much like writing Python. To make it a bit less like writing Python, we should consider wrapping the `ArgumentParser` instance in a helper function.

[1]: https://github.com/opensafely/airmid-data-development/blob/5b29a5360353edb1b1a431bd2d1398c9b4ea47e9/project.yaml#L79-L88
[2]: https://github.com/opensafely/airmid-data-development/blob/5b29a5360353edb1b1a431bd2d1398c9b4ea47e9/analysis/model_data_structure/dataset_definition.py#L8-L20
